### ISSUE TITLE
Design Of Website

### ISSUE THREAD

**Issue by vipinkhushu** [Manan-YMCA/ElementsCulmyca2017Website#1]
Includes:-
1. Wireframe of website i.e. Appearance of website
2. Choosing framework ([bootstrap](http://getbootstrap.com/) or [materialize](http://materializecss.com/))
3. Assigning work to every member

**Comment by aakashverma12** [comment]
Interested

**Comment by scorpion-ajay** [comment]
interested :)

**Comment by vipinkhushu** [comment]
@aakashverma12 @virtualajay Cool. Will get in touch with you soon

**Comment by namansachdeva** [comment]
![img_20170120_241125336](https://cloud.githubusercontent.com/assets/18380175/22120425/a17e006e-dea5-11e6-8998-f93879d4eb0b.jpg)

**Comment by poojagarg123** [comment]
Interested:)

**Comment by Twinkle-Anand** [comment]
Interested

**Comment by Shubhamgoel123** [comment]
Interested

**Comment by vipinkhushu** [comment]
@akankshadiwedy Take a lead here and finalize the UI asap.... And i liked this @namansachdeva 's design of credit card.. try to implement it somewhere...
