### ISSUE TITLE
Responsiveness Check

### ISSUE THREAD

**Issue by namansachdeva** [Manan-YMCA/ElementsCulmyca2017Website#10]
Mobile Site has issues in Facebook feed, Categories and Debit Card image.

**Comment by vipinkhushu** [comment]
Lising all responsive bugs:-
1. The right side extra portion ( Filed by @gunpreet34  )
![whatsapp image 2017-02-24 at 11 51 30 am](https://cloud.githubusercontent.com/assets/11455744/23293864/a6dd0ba4-fa8e-11e6-9f65-30ce1fc8c4f4.jpeg)

2. Category name sliding over EC logo ( Filed by #5 @SidharthMehta )
![image 1](https://cloud.githubusercontent.com/assets/11455744/23294628/4a7fb5d8-fa92-11e6-8f0e-97a1558170fa.png)

**Comment by vipinkhushu** [comment]
3.  Facebook plugin not responsive (Filed by @satwickdash 
![whatsapp image 2017-02-24 at 1 19 20 pm](https://cloud.githubusercontent.com/assets/11455744/23295022/6a85825c-fa94-11e6-9797-f07f84aae16d.jpeg)
 )

**Comment by aakashverma12** [comment]
Fixed https://github.com/Manan-YMCA/ElementsCulmyca2017Website/commit/db1150503c75fff3bf0ebc028ed7ea022cd066af

**Comment by vipinkhushu** [comment]
@aakashverma12 Please specify which part of bug is solved..

**Comment by aakashverma12** [comment]
actually the site was sliding right due to the facebook plugin, so both are solved

**Comment by vipinkhushu** [comment]
1, 2 Fixed 
3 Pending

**Comment by vipinkhushu** [comment]
Bug reported by @namansachdeva "Mobile Site has issues in Facebook feed, Categories and Debit Card image." Fixed https://github.com/Manan-YMCA/ElementsCulmyca2017Website/commit/94fb7e09b4253db8637dada3d5ed9930ca987e4b

**Comment by vipinkhushu** [comment]
#10 
Subpart 1 by @gunpreet34 fixed
Subpart 2 by @SidharthMehta fixed
Subpart 3 by @satwickdash fixed
