### ISSUE TITLE
Navigation bar contains duplicate links

### ISSUE THREAD

**Issue by sonalgupta276** [Manan-YMCA/ElementsCulmyca2017Website#12]
![screenshot 8](https://cloud.githubusercontent.com/assets/11365625/23292740/e0060a40-fa87-11e6-85de-12340494993d.png)

After you click on 'The Team' on Navigation bar from home page, you land on page as shown in the screenshot. The navigation bar has two times 'The Team' which shouldn't have been there.

**Comment by vipinkhushu** [comment]
Bug fixed by @aakashverma12  
Refer: https://github.com/Manan-YMCA/ElementsCulmyca2017Website/commit/d563f1a133ec9461b00ddac27fd77ba648b41e63
