### ISSUE TITLE
Compressing All Media Files

### ISSUE THREAD

**Issue by vipinkhushu** [Manan-YMCA/ElementsCulmyca2017Website#13]
We need to reduce website initial load time,
So we need to
1. Compress all media files, such as images
2. Implement caching of css, js files

**Comment by 6Rebel** [comment]
we need to change every image of every event.
and what is that meaningless words NA TO NA NA.

**Comment by namansachdeva** [comment]
Time, I guess.

**Comment by namansachdeva** [comment]
Time it is, I guess.

**Comment by vipinkhushu** [comment]
we can use http://compressjpeg.com/
