### ISSUE TITLE
No validations in the form while registering for the event.

### ISSUE THREAD

**Issue by sonalgupta276** [Manan-YMCA/ElementsCulmyca2017Website#14]
When you register for a event, no validations on email and phone no.
A user with phone no. less than 10 digits is able to register.
No criteria for email.
Full name of user is accepted in numeric.
Expected: Validations should be checked and proper validation message should appear to user.

**Comment by himani-kansal** [comment]
Resolved #14

**Comment by vipinkhushu** [comment]
#14 resolved & Tested
