### ISSUE TITLE
Cosmetic Enhancements

### ISSUE THREAD

**Issue by vipinkhushu** [Manan-YMCA/ElementsCulmyca2017Website#17]
Listing some cosmetic enhancements:-
1. The Instagram logo on top right corner, shows no colour change effect on hover, but facebook and twitter does.
2. The nav bar has onclick link bgcolor update style property with which the bg color remains to be white even when we are not in that section. 
3. Center aligning names of categories on index.html page
4. Setting a event pic for each category, currently event category event page has some camera pic... we need to set a different image for each category.

**Comment by aakashverma12** [comment]
why not ask The pics from respective clubs

**Comment by vipinkhushu** [comment]
Fixed #17 and verified
