### ISSUE TITLE
Coding The Frontend

### ISSUE THREAD

**Issue by vipinkhushu** [Manan-YMCA/ElementsCulmyca2017Website#2]
Requires:-
1. HTML CSS
2. Knowledge of using front end frameworks
3. Javascript
4. Jquery
5. Ajax

**Comment by aakashverma12** [comment]
interested

**Comment by scorpion-ajay** [comment]
commented :p

**Comment by vipinkhushu** [comment]
Will start work on this as soon as design issue is closed :)

**Comment by vipinkhushu** [comment]
@akankshadiwedy @himani-kansal @availchet Here is the data sheet for website https://docs.google.com/spreadsheets/d/1R8DKS2UPNTAS6haPF4wWLC1MCsn5Ozydi4dsnqroeAE/edit?usp=sharing
