### ISSUE TITLE
Linking the frontend with REST API backend

### ISSUE THREAD

**Issue by vipinkhushu** [Manan-YMCA/ElementsCulmyca2017Website#3]
Requires:-
1. Jquery 
2. Knowledge of JSON Parsing

**Comment by namansachdeva** [comment]
I'm interested!

**Comment by vipinkhushu** [comment]
@namansachdeva Familiar with ajax jquery??

**Comment by namansachdeva** [comment]
I know JSON parsing and JQuery to some extent. AJAX nahi pata.

**Comment by vipinkhushu** [comment]
@namansachdeva Study AJAX request to fetch and send data then.. its pretty easy
